name: 48 - Reusable workflow 1

on:
  workflow_call:

jobs:
  job-reusable-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Show Current Branch
        run: echo "Current branch is: ${{ github.ref }}"          
      - uses: volta-cli/action@v1
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: ls -la
      - run: npm test
      - run: npm run build --if-present
        env:
          CI: true        
  # job-reusable-2:
  #   runs-on: ubuntu-latest
  #   steps:
      # - uses: actions/checkout@v2.3.4 # Necessary to access local action
      # - name: Local Action Call
      #   id: local-action
      #   uses: ./.github/actions/local-action
      #   with:
      #     name: "World"
      # - name: Local Action Output
      #   run: echo "${{ steps.local-action.outputs.random }}"
