name: 48 - Reusable workflow 1

on:
  workflow_call:

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/feat/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: volta-cli/action@v1
      - run: npm ci --no-audit
      - run: npm run lint --if-present
      - run: ls -la
      - run: npm test
      - run: npm run build --if-present
        env:
          CI: true
      - name: Run for feat/* branches
        if: startsWith(github.ref, 'refs/heads/feat/')
        run: echo "This runs only for feat/* branches"

      - name: Run for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only for the main branch"          

  # job-reusable-2:
  #   runs-on: ubuntu-latest
  #   steps:
      # - uses: actions/checkout@v2.3.4 # Necessary to access local action
      # - name: Local Action Call
      #   id: local-action
      #   uses: ./.github/actions/local-action
      #   with:
      #     name: "World"
      # - name: Local Action Output
      #   run: echo "${{ steps.local-action.outputs.random }}"
